@hostname = localhost
@port = 8090
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MDM0Mjg3NTM3MCIsInJvbGVzIjpbXSwiaWF0IjoxNTczNDgwMDU5LCJleHAiOjE1NzM1MTYwNTl9.e_9T_sKF1C4QAH7C2OAGs55RpqSEa2_IM_g-ehftcdo

###

@name = hello

POST http://{{host}}/login HTTP/1.1
content-type: application/json

{
    "cpf": "60342875370",
    "password": "123456"
}

###

GET http://{{host}}/usuario/1 HTTP/1.1
Authorization: {{token}}

###
GET http://{{host}}/treinamento/listar HTTP/1.1
Authorization: {{token}}