@hostname = localhost
@port = 8090
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2MDM0Mjg3NTM3MCIsInJvbGVzIjpbXSwiaWF0IjoxNTczNDE2OTY0LCJleHAiOjE1NzM0NTI5NjR9._eqkTON97eTMkZfVI6_hOCiu734K-Jg5f0Z36SzZC_k

###

@name = hello

POST https://{{host}}/login HTTP/1.1
content-type: application/json

{
    "cpf": "60342875370",
    "password": "123456"
}

###

GET http://{{host}}/usuario/1 HTTP/1.1
Authorization: {{token}}

###
GET http://{{host}}/treinamento/listar HTTP/1.1
Authorization: {{token}}