@hostname = localhost
@port = 8090
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@token = Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMTIzODA1MDMzNiIsInJvbGVzIjpbXSwiaWF0IjoxNTc0NzcyMjg3LCJleHAiOjE1NzQ4MDgyODd9.8Fd7wvmkCa8IflF3A0NeBuWzX68PA4OxAtWQrXK1GCY

###

@name = hello

POST http://{{host}}/login HTTP/1.1
content-type: application/json

{
    "cpf": "21238050336",
    "password": "123456"
}

###

GET http://{{host}}/usuario/1 HTTP/1.1
Authorization: {{token}}

###

GET http://{{host}}/funcionario/listar/1 HTTP/1.1
Authorization: {{token}}

###
GET http://{{host}}/treinamento/listar HTTP/1.1
Authorization: {{token}}

###
POST http://{{host}}/treinamento HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "descricao": "Teste",
    "classificacao": "REQUERIDO"
}

###
DELETE  http://{{host}}/treinamento/excluir/5 HTTP/1.1
Authorization: {{token}}

###
GET http://{{host}}/beneficio/listar HTTP/1.1
Authorization: {{token}}

###
POST http://{{host}}/beneficio HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "titulo": "Título beneficio2",
    "informacoes": "Teste informação2",
    "valor": 45.12
}

###
DELETE  http://{{host}}/beneficio/excluir/8 HTTP/1.1
Authorization: {{token}}

###
GET  http://{{host}}/cargo/1 HTTP/1.1
Authorization: {{token}}

###
GET  http://{{host}}/relatorio/cargos HTTP/1.1
Authorization: {{token}}

###
GET  http://{{host}}/relatorio/funcionarios HTTP/1.1
Authorization: {{token}}


###

PUT  http://{{host}}/cargo
Authorization: {{token}}
content-type: application/json

{
    "id": 4,
    "titulacao": "Programador Java Senior",
    "area": "computação",
    "experienciaMinima": "2 anos",      
    "missao": "programar",
    "salarioBaseMaximo": 1200,
    "salarioBaseMinimo": 5000,
    "unidade": "Fortaleza",
    "atividades": [
        { "titulo": "aaa", "descricao": "desc aaa"}
    ]
}


###

POST  http://{{host}}/atividade
Authorization: {{token}}
content-type: application/json

 {"titulo": "aaa", "descricao": "desc aaa"}